select * from tagList order by tag;

insert into tagList values(1, 'INTJ');
insert into tagList values(2, 'INTP');
insert into tagList values(3, 'ENTJ');
insert into tagList values(4, 'ENTP');
insert into tagList values(5, 'INFJ');
insert into tagList values(6, 'INFP');
insert into tagList values(7, 'ENFJ');
insert into tagList values(8, 'ENFP');
insert into tagList values(9, 'ISTJ');
insert into tagList values(10, 'ISFJ');
insert into tagList values(11, 'ESTJ');
insert into tagList values(12, 'ESFJ');
insert into tagList values(13, 'ISTP');
insert into tagList values(14, 'ISFP');
insert into tagList values(15, 'ESTP');
insert into tagList values(16, 'ESFP');

insert into tagList values(17, '연극');
insert into tagList values(18, '산책');
insert into tagList values(19, '국내여행');
insert into tagList values(20, '해외여행');
insert into tagList values(21, '스포츠관람');
insert into tagList values(22, '근교드라이브');
insert into tagList values(23, '운동');
insert into tagList values(24, '전시회 관람');
insert into tagList values(25, '게임');
insert into tagList values(26, '봉사활동');
insert into tagList values(27, '캠핑');

insert into tagList values(28, 'PC게임');
insert into tagList values(29, '콘솔게임');
insert into tagList values(30, '피트니스');
insert into tagList values(31, '등산');
insert into tagList values(32, '클라이밍');
insert into tagList values(33, '서예');
insert into tagList values(34, '축구');
insert into tagList values(35, '농구');
insert into tagList values(36, '야구');
insert into tagList values(37, '배구');
insert into tagList values(38, '독서');
insert into tagList values(39, '음악감상');
insert into tagList values(40, '댄스');
insert into tagList values(41, '사이클링');
insert into tagList values(42, '수영');
insert into tagList values(43, '악기 연주');
insert into tagList values(44, '서핑');
insert into tagList values(45, '베이킹');
insert into tagList values(46, '글쓰기');
insert into tagList values(47, '요리');
insert into tagList values(48, '블로그');
insert into tagList values(49, '식물 가꾸기');
insert into tagList values(50, '요가');
insert into tagList values(51, '사진');
insert into tagList values(52, '골프');
insert into tagList values(53, '승마');

insert into tagList values(54, '콘서트');
insert into tagList values(55, '미술관');
insert into tagList values(56, 'PC방');
insert into tagList values(57, '맛집 탐방');
insert into tagList values(58, '인스타그래머블 카페');
insert into tagList values(59, '공원');
insert into tagList values(60, '집 밖은 위험해');
insert into tagList values(61, 'VR 체험');
insert into tagList values(62, '박물관');
insert into tagList values(63, '방 탈출');
insert into tagList values(64, 'CLUB');
insert into tagList values(65, 'BAR');
insert into tagList values(66, '노래방');
insert into tagList values(67, '만화카페');

insert into tagList values(68, '심심할 때 수다');
insert into tagList values(69, '솔직한 대화');
insert into tagList values(70, '커피 한 잔');
insert into tagList values(71, '동네 산책');
insert into tagList values(72, '런닝');
insert into tagList values(73, '홈트레이닝');
insert into tagList values(74, '브런치');
insert into tagList values(75, '쇼핑');
insert into tagList values(76, '페스티벌');
insert into tagList values(77, '낚시');
insert into tagList values(78, '크로스핏');
insert into tagList values(79, 'e스포츠');
insert into tagList values(80, '채식');
insert into tagList values(81, '비건');
insert into tagList values(82, '세계여행');
insert into tagList values(83, '패션');
insert into tagList values(84, '애니메이션');
insert into tagList values(85, '별자리');
insert into tagList values(86, '디저트');
insert into tagList values(87, '예술');
insert into tagList values(88, '먹방');
insert into tagList values(89, '대식가');
insert into tagList values(90, '로멘스');
insert into tagList values(91, '코미디');
insert into tagList values(92, '애견인');
insert into tagList values(93, '애묘인');
insert into tagList values(94, '동물 애호가');
insert into tagList values(95, '와인');
insert into tagList values(96, '술 한잔');
insert into tagList values(97, '수제 맥주');
insert into tagList values(98, '차 한잔');
insert into tagList values(99, '영화관');
insert into tagList values(100, '넷플릭스');
insert into tagList values(101, '디즈니');
insert into tagList values(102, '예능');
insert into tagList values(103, '파티');
insert into tagList values(104, '언어 교환');
